namespace Attendance.Domain.ValueObjects;

/// <summary>
/// A position as reported by a mobile device, together with the metadata needed
/// to judge how much to trust it.
/// </summary>
/// <remarks>
/// <para>
/// Everything here arrives from an untrusted client (Claude.md §65), including
/// the flags that say the position was faked. A device that is lying about its
/// location will also lie about <see cref="IsMocked"/>. These signals raise the
/// cost of cheating; they do not make the position trustworthy.
/// </para>
/// <para>
/// <b>Accuracy is not comparable across platforms.</b> Android documents
/// <c>Location.getAccuracy()</c> as a radius at 68% confidence — roughly one
/// time in three the true position is outside it. Apple documents
/// <c>CLLocation.horizontalAccuracy</c> only as "the radius of uncertainty",
/// with no confidence level stated. The platform is therefore carried alongside
/// the number so that reports and any future tuning can separate the two rather
/// than averaging values that do not mean the same thing.
/// </para>
/// </remarks>
public readonly record struct ReportedPosition
{
    /// <summary>
    /// Creates a reported position.
    /// </summary>
    /// <param name="coordinates">The validated position.</param>
    /// <param name="accuracyMeters">
    /// The device's own horizontal accuracy estimate, or <c>null</c> when the
    /// device did not supply one. Null is meaningful: it means "unknown", which
    /// the policy treats as insufficient rather than as "perfect".
    /// </param>
    /// <param name="platform">The reporting platform.</param>
    /// <param name="isMocked">
    /// Android reported the position came from a mock provider.
    /// </param>
    /// <param name="isSimulatedBySoftware">
    /// iOS 15 or later reported the position was generated by on-device
    /// software simulation.
    /// </param>
    public ReportedPosition(
        Coordinates coordinates,
        double? accuracyMeters,
        DevicePlatform platform,
        bool isMocked = false,
        bool isSimulatedBySoftware = false)
    {
        Coordinates = coordinates;
        AccuracyMeters = accuracyMeters;
        Platform = platform;
        IsMocked = isMocked;
        IsSimulatedBySoftware = isSimulatedBySoftware;
    }

    /// <summary>The validated position.</summary>
    public Coordinates Coordinates { get; }

    /// <summary>
    /// The device's horizontal accuracy estimate in metres, or <c>null</c> if
    /// it was not supplied.
    /// </summary>
    public double? AccuracyMeters { get; }

    /// <summary>The platform that produced the reading.</summary>
    public DevicePlatform Platform { get; }

    /// <summary>Android: the position came from a mock location provider.</summary>
    public bool IsMocked { get; }

    /// <summary>iOS 15+: the position was simulated by software.</summary>
    public bool IsSimulatedBySoftware { get; }

    /// <summary>
    /// Whether either platform flagged the reading as artificially produced.
    /// </summary>
    public bool IsSourceUntrusted => IsMocked || IsSimulatedBySoftware;

    /// <summary>
    /// Whether the device supplied a usable accuracy estimate.
    /// </summary>
    /// <remarks>
    /// A non-positive value is treated as missing. Apple documents a negative
    /// <c>horizontalAccuracy</c> as meaning the coordinates are invalid, and a
    /// zero-metre estimate is not a claim any honest device makes.
    /// </remarks>
    public bool HasUsableAccuracy =>
        AccuracyMeters is { } accuracy && double.IsFinite(accuracy) && accuracy > 0d;

    /// <summary>
    /// Returns a description safe for diagnostics, with no coordinates in it.
    /// </summary>
    public override string ToString() =>
        $"ReportedPosition(platform={Platform}, accuracy={(HasUsableAccuracy ? AccuracyMeters!.Value.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture) : "unknown")}m, untrustedSource={IsSourceUntrusted})";
}

/// <summary>
/// The mobile platform a reading came from.
/// </summary>
/// <remarks>
/// Values match the <c>Platform</c> column on <c>core.Device</c> and
/// <c>core.AttendanceEvent</c>.
/// </remarks>
public enum DevicePlatform
{
    /// <summary>Not stated.</summary>
    Unknown = 0,

    /// <summary>Android.</summary>
    Android = 1,

    /// <summary>iOS.</summary>
    Ios = 2,
}
