using Attendance.Application.Abstractions;
using Attendance.Application.Services;
using Attendance.Domain.Enums;
using Attendance.Domain.Services;
using Attendance.Domain.ValueObjects;

namespace Attendance.Application.Tests;

/// <summary>
/// Test doubles for the ports the attendance handlers depend on.
/// </summary>
/// <remarks>
/// Hand-written rather than generated by a mocking library, because these tests
/// are mostly about <b>order and timing</b> — which port was called, and before
/// what. Recording the call sequence explicitly makes those assertions readable,
/// and avoids a dependency whose failure messages would be harder to act on.
/// </remarks>
internal sealed class AttendanceTestHarness
{
    public const string UserId = "jane.doe";
    public const string Password = "correct horse battery staple";
    public const string Code = "123456";
    public const int MobileUserId = 42;
    public const int DeviceId = 7;
    public const int OfficeLocationId = 3;

    /// <summary>Ports called, in order, so sequencing can be asserted.</summary>
    public List<string> Calls { get; } = [];

    public FakePolicyProvider Policy { get; } = new();
    public FakeLockout Lockout { get; }
    public FakeCredentialValidator Credentials { get; }
    public FakeMobileUsers Users { get; }
    public FakeSecretProtector Secrets { get; }
    public FakeTotpVerifier Totp { get; }
    public FakeMfaCredentials Mfa { get; }
    public FakeOfficeLocations Offices { get; }
    public FakeIdempotencyStore Idempotency { get; }
    public FakeAttendanceRepository Attendance { get; }
    public FakeSecurityEventRecorder SecurityEvents { get; }

    /// <summary>
    /// The real authentication sequence over faked ports.
    /// </summary>
    /// <remarks>
    /// Deliberately the production <see cref="EmployeeAuthenticator"/> rather
    /// than a stub: the ordering guarantees these tests exist to protect live
    /// inside it, and a stub would assert nothing about them.
    /// </remarks>
    public EmployeeAuthenticator Authenticator { get; }

    public FakeDeviceRepository Devices { get; }
    public FakeAttestationVerifier Attestation { get; }
    public FakeSignatureVerifier Signatures { get; }
    public FakeMobileConfiguration Configuration { get; }

    public AttendanceTestHarness()
    {
        Lockout = new FakeLockout(Calls);
        Credentials = new FakeCredentialValidator(Calls);
        Users = new FakeMobileUsers(Calls);
        Secrets = new FakeSecretProtector(Calls);
        Totp = new FakeTotpVerifier(Calls);
        Mfa = new FakeMfaCredentials(Calls);
        Offices = new FakeOfficeLocations(Calls);
        Idempotency = new FakeIdempotencyStore(Calls);
        Attendance = new FakeAttendanceRepository(Calls);
        SecurityEvents = new FakeSecurityEventRecorder(Calls);

        Devices = new FakeDeviceRepository(Calls);
        Attestation = new FakeAttestationVerifier(Calls);
        Signatures = new FakeSignatureVerifier(Calls);
        Configuration = new FakeMobileConfiguration(Calls);

        Authenticator = new EmployeeAuthenticator(
            Lockout, Credentials, Users, Secrets, Totp, Mfa, SecurityEvents);
    }

    /// <summary>A well-formed uncompressed P-256 point: 0x04 followed by X and Y.</summary>
    public static byte[] WellFormedPublicKey()
    {
        byte[] key = new byte[65];
        key[0] = 0x04;

        for (int i = 1; i < key.Length; i++)
        {
            key[i] = (byte)i;
        }

        return key;
    }

    /// <summary>A position two metres from the office, with good accuracy.</summary>
    public static ReportedPosition AcceptablePosition =>
        new(Coordinates.Create(6.465440d, 3.406448d), accuracyMeters: 3d, DevicePlatform.Android);

    /// <summary>A position far outside any office.</summary>
    public static ReportedPosition DistantPosition =>
        new(Coordinates.Create(6.600000d, 3.500000d), accuracyMeters: 3d, DevicePlatform.Android);

    internal sealed class FakePolicyProvider : IAttendancePolicyProvider
    {
        public AttendancePolicy Policy { get; set; } = new(
            LocationAccuracyPolicy.DistanceAndAccuracyThreshold,
            MaxAcceptedAccuracyMeters: null,
            RejectUntrustedLocationSource: true,
            MobileLockoutThreshold: 5,
            MobileLockoutMinutes: 15,
            SignatureSkewSeconds: 120,
            CollapseCredentialErrorCodes: true,
            RequireHardwareAttestationAndroid: true,
            RequireHardwareAttestationIos: true,
            DeviceRegistrationRequiresApproval: true,
            ChallengeLifetimeSeconds: 300,
            MinimumAppVersion: null,
            TotpStepTolerance: 1);

        public Task<AttendancePolicy> GetAsync(CancellationToken cancellationToken) => Task.FromResult(Policy);
    }

    internal sealed class FakeLockout : IAuthenticationAttemptRepository
    {
        private readonly List<string> _calls;

        public FakeLockout(List<string> calls) => _calls = calls;

        public bool IsLockedOut { get; set; }

        public bool LocksOnNextFailure { get; set; }

        public int FailuresRegistered { get; private set; }

        public int ResetCount { get; private set; }

        public Task<LockoutState> CheckAsync(AuthenticationSubject subject, string subjectKey, CancellationToken cancellationToken)
        {
            _calls.Add("lockout.check");
            return Task.FromResult(new LockoutState(IsLockedOut, IsLockedOut ? DateTimeOffset.UtcNow.AddMinutes(15) : null, 0));
        }

        public Task<LockoutState> RegisterFailureAsync(
            AuthenticationSubject subject, string subjectKey, int threshold, int lockoutMinutes, CancellationToken cancellationToken)
        {
            _calls.Add("lockout.registerFailure");
            FailuresRegistered++;
            return Task.FromResult(new LockoutState(LocksOnNextFailure, null, FailuresRegistered));
        }

        public Task ResetAsync(AuthenticationSubject subject, string subjectKey, CancellationToken cancellationToken)
        {
            _calls.Add("lockout.reset");
            ResetCount++;
            return Task.CompletedTask;
        }
    }

    internal sealed class FakeCredentialValidator : IEmployeeCredentialValidator
    {
        private readonly List<string> _calls;

        public FakeCredentialValidator(List<string> calls) => _calls = calls;

        public CredentialValidationOutcome Outcome { get; set; } = CredentialValidationOutcome.Valid;

        public Task<CredentialValidationResult> ValidateAsync(string userId, string password, CancellationToken cancellationToken)
        {
            _calls.Add("credentials.validate");

            return Task.FromResult(Outcome == CredentialValidationOutcome.Valid
                ? CredentialValidationResult.Success(MobileUserId, requiresPasswordChange: false)
                : CredentialValidationResult.Failure(Outcome, MobileUserId));
        }
    }

    internal sealed class FakeMobileUsers : IMobileUserRepository
    {
        private readonly List<string> _calls;

        public FakeMobileUsers(List<string> calls) => _calls = calls;

        public bool HasMfaEnrolment { get; set; } = true;

        public Task<MobileUserAuthenticationRecord?> GetForAuthenticationAsync(string userId, CancellationToken cancellationToken)
        {
            _calls.Add("users.getForAuthentication");

            MfaEnrolment? mfa = HasMfaEnrolment
                ? new MfaEnrolment(1, [0x01, 0x02], TotpParameters.Default, LastAcceptedTimeStep: null)
                : null;

            return Task.FromResult<MobileUserAuthenticationRecord?>(
                new MobileUserAuthenticationRecord(MobileUserId, Guid.NewGuid(), userId, IsActive: true, Credential: null, Mfa: mfa));
        }
    }

    internal sealed class FakeSecretProtector : ISecretProtector
    {
        private readonly List<string> _calls;

        public FakeSecretProtector(List<string> calls) => _calls = calls;

        public bool CanUnprotect { get; set; } = true;

        public byte[] Protect(string purpose, ReadOnlySpan<byte> plaintext) => plaintext.ToArray();

        public bool TryUnprotect(string purpose, byte[] protectedPayload, out byte[] plaintext)
        {
            _calls.Add("secrets.unprotect");
            plaintext = CanUnprotect ? [0x0A, 0x0B, 0x0C] : [];
            return CanUnprotect;
        }
    }

    internal sealed class FakeTotpVerifier : ITotpVerifier
    {
        private readonly List<string> _calls;

        public FakeTotpVerifier(List<string> calls) => _calls = calls;

        public bool IsValid { get; set; } = true;

        public long MatchedTimeStep { get; set; } = 58_000_000L;

        public TotpVerificationResult Verify(
            ReadOnlySpan<byte> secret, string code, TotpParameters parameters, int stepTolerance)
        {
            _calls.Add("totp.verify");
            return IsValid ? TotpVerificationResult.Valid(MatchedTimeStep) : TotpVerificationResult.Invalid;
        }
    }

    internal sealed class FakeMfaCredentials : IMfaCredentialRepository
    {
        private readonly List<string> _calls;

        public FakeMfaCredentials(List<string> calls) => _calls = calls;

        public AttendanceResultCode ConsumeResult { get; set; } = AttendanceResultCode.Success;

        public Task<AttendanceResultCode> TryConsumeTimeStepAsync(int mobileUserId, long timeStep, CancellationToken cancellationToken)
        {
            _calls.Add("mfa.consumeTimeStep");
            return Task.FromResult(ConsumeResult);
        }
    }

    internal sealed class FakeOfficeLocations : IOfficeLocationRepository
    {
        private readonly List<string> _calls;

        public FakeOfficeLocations(List<string> calls) => _calls = calls;

        public IReadOnlyList<OfficeLocationCandidate> Offices { get; set; } =
        [
            new OfficeLocationCandidate(OfficeLocationId, Coordinates.Create(6.465422d, 3.406448d), 5d),
        ];

        public Task<IReadOnlyList<OfficeLocationCandidate>> GetActiveAsync(CancellationToken cancellationToken)
        {
            _calls.Add("offices.getActive");
            return Task.FromResult(Offices);
        }

        public void InvalidateCache() { }
    }

    internal sealed class FakeIdempotencyStore : IIdempotencyStore
    {
        private readonly List<string> _calls;

        public FakeIdempotencyStore(List<string> calls) => _calls = calls;

        public IdempotencyDisposition Disposition { get; set; } = IdempotencyDisposition.Proceed;

        public int? StoredResultCode { get; set; }

        public int CompletedCount { get; private set; }

        public int? CompletedWithResultCode { get; private set; }

        public Task<IdempotencyClaim> TryBeginAsync(
            int deviceId, Guid idempotencyKey, IdempotentEndpoint endpoint, ReadOnlyMemory<byte> requestHash, CancellationToken cancellationToken)
        {
            _calls.Add("idempotency.tryBegin");
            return Task.FromResult(new IdempotencyClaim(Disposition, StoredResultCode, null));
        }

        public Task CompleteAsync(int deviceId, Guid idempotencyKey, int resultCode, string? responsePayload, CancellationToken cancellationToken)
        {
            _calls.Add("idempotency.complete");
            CompletedCount++;
            CompletedWithResultCode = resultCode;
            return Task.CompletedTask;
        }
    }

    internal sealed class FakeAttendanceRepository : IAttendanceRepository
    {
        private readonly List<string> _calls;

        public FakeAttendanceRepository(List<string> calls) => _calls = calls;

        public AttendanceResultCode ClockInResult { get; set; } = AttendanceResultCode.Success;

        public AttendanceResultCode ClockOutResult { get; set; } = AttendanceResultCode.Success;

        public LocationEvidence? LastEvidence { get; private set; }

        public Task<AttendanceStatus> GetCurrentStatusAsync(int mobileUserId, CancellationToken cancellationToken)
        {
            _calls.Add("attendance.getCurrentStatus");

            return Task.FromResult(new AttendanceStatus(
                AttendanceResultCode.Success, AttendanceState.NotClockedIn, null, DateTimeOffset.UtcNow, null, null, null, null, null));
        }

        public Task<ClockInOutcome> ClockInAsync(ClockInRequest request, CancellationToken cancellationToken)
        {
            _calls.Add("attendance.clockIn");
            LastEvidence = request.Evidence;

            return Task.FromResult(ClockInResult == AttendanceResultCode.Success
                ? new ClockInOutcome(ClockInResult, Guid.NewGuid(), DateOnly.FromDateTime(DateTime.UtcNow), DateTimeOffset.UtcNow, false)
                : new ClockInOutcome(ClockInResult, null, null, null, null));
        }

        public Task<ClockOutOutcome> ClockOutAsync(ClockOutRequest request, CancellationToken cancellationToken)
        {
            _calls.Add("attendance.clockOut");
            LastEvidence = request.Evidence;

            return Task.FromResult(ClockOutResult == AttendanceResultCode.Success
                ? new ClockOutOutcome(ClockOutResult, Guid.NewGuid(), DateOnly.FromDateTime(DateTime.UtcNow), DateTimeOffset.UtcNow.AddHours(-8), DateTimeOffset.UtcNow, 480, false)
                : new ClockOutOutcome(ClockOutResult, null, null, null, null, null, null));
        }
    }

    internal sealed class FakeDeviceRepository : IDeviceRepository
    {
        private readonly List<string> _calls;

        public FakeDeviceRepository(List<string> calls)
        {
            _calls = calls;
            StatusRecord = ActiveStatus();
        }

        /// <summary>The status to return; <see langword="null"/> means no such device.</summary>
        public DeviceStatusRecord? StatusRecord { get; set; }

        public AttendanceResultCode RegisterResult { get; set; } = AttendanceResultCode.RegistrationPendingApproval;

        public DeviceStatus RegisteredStatus { get; set; } = DeviceStatus.PendingApproval;

        /// <summary>The last registration request, so its contents can be asserted.</summary>
        public DeviceRegistrationRequest? LastRegistration { get; private set; }

        public List<byte[]> IssuedChallenges { get; } = [];

        public int LastChallengeLifetimeSeconds { get; private set; }

        public int? TouchedDeviceId { get; private set; }

        public string? TouchedAppVersion { get; private set; }

        public Task<RegistrationChallenge> IssueRegistrationChallengeAsync(
            ReadOnlyMemory<byte> challenge, int lifetimeSeconds, byte[]? issuedToIpHash, CancellationToken cancellationToken)
        {
            _calls.Add("devices.issueChallenge");
            IssuedChallenges.Add(challenge.ToArray());
            LastChallengeLifetimeSeconds = lifetimeSeconds;

            return Task.FromResult(new RegistrationChallenge(
                AttendanceResultCode.Success, Guid.NewGuid(), DateTimeOffset.UtcNow.AddSeconds(lifetimeSeconds)));
        }

        public Task<DeviceRegistrationOutcome> RegisterAsync(
            DeviceRegistrationRequest request, CancellationToken cancellationToken)
        {
            _calls.Add("devices.register");
            LastRegistration = request;

            return Task.FromResult(
                RegisterResult is AttendanceResultCode.Success or AttendanceResultCode.RegistrationPendingApproval
                    ? new DeviceRegistrationOutcome(RegisterResult, Guid.NewGuid(), RegisteredStatus)
                    : new DeviceRegistrationOutcome(RegisterResult, null, null));
        }

        public Task<DeviceStatusRecord?> GetStatusAsync(Guid devicePublicId, CancellationToken cancellationToken)
        {
            _calls.Add("devices.getStatus");
            return Task.FromResult(StatusRecord);
        }

        /// <summary>An approved, usable device.</summary>
        public static DeviceStatusRecord ActiveStatus() =>
            new(AttendanceResultCode.Success, Guid.NewGuid(), DeviceStatus.Active, AttestationLevel.Hardware,
                DateTimeOffset.UtcNow.AddDays(-7), DateTimeOffset.UtcNow.AddDays(-7), null, null,
                Guid.NewGuid(), UserId, EmployeeActive: true, DateTimeOffset.UtcNow);

        /// <summary>A device that was revoked, with the reason its holder is shown.</summary>
        public static DeviceStatusRecord RevokedStatus(string reason) =>
            new(AttendanceResultCode.Success, Guid.NewGuid(), DeviceStatus.Revoked, AttestationLevel.Hardware,
                DateTimeOffset.UtcNow.AddDays(-7), DateTimeOffset.UtcNow.AddDays(-7), DateTimeOffset.UtcNow.AddHours(-2),
                reason, Guid.NewGuid(), UserId, EmployeeActive: true, DateTimeOffset.UtcNow);

        public Task<DeviceVerificationRecord?> GetForSignatureVerificationAsync(
            Guid devicePublicId, CancellationToken cancellationToken)
        {
            _calls.Add("devices.getForSignatureVerification");

            return Task.FromResult<DeviceVerificationRecord?>(new DeviceVerificationRecord(
                AttendanceResultCode.Success, DeviceId, devicePublicId, MobileUserId, Guid.NewGuid(), UserId,
                WellFormedPublicKey(), DeviceStatus.Active, AttestationLevel.Hardware, DevicePlatform.Android, "1.0.0"));
        }

        public Task TouchLastSeenAsync(
            int deviceId, string? appVersion, string? osVersion, CancellationToken cancellationToken)
        {
            _calls.Add("devices.touchLastSeen");
            TouchedDeviceId = deviceId;
            TouchedAppVersion = appVersion;
            return Task.CompletedTask;
        }
    }

    internal sealed class FakeMobileConfiguration : IMobileConfigurationRepository
    {
        private readonly List<string> _calls;

        public FakeMobileConfiguration(List<string> calls) => _calls = calls;

        public bool ClockInConfigured { get; set; } = true;

        public bool ClockOutConfigured { get; set; } = true;

        public List<MobileSetting> Settings { get; } =
        [
            new MobileSetting("Location.RejectMockedLocations", "true", "bool"),
            new MobileSetting("Attendance.ClockInCloseTime", null, "time"),
        ];

        public Task<MobileRuntimeConfiguration> GetRuntimeConfigurationAsync(CancellationToken cancellationToken)
        {
            _calls.Add("configuration.getRuntime");

            return Task.FromResult(new MobileRuntimeConfiguration(
                Settings, ClockInConfigured, ClockOutConfigured, DateTimeOffset.UtcNow));
        }
    }

    internal sealed class FakeAttestationVerifier : IDeviceAttestationVerifier
    {
        private readonly List<string> _calls;

        public FakeAttestationVerifier(List<string> calls) => _calls = calls;

        public bool IsAccepted { get; set; } = true;

        public AttestationLevel Level { get; set; } = AttestationLevel.Hardware;

        public string ReasonCode { get; set; } = "ATTESTATION_CHAIN_INVALID";

        public Task<AttestationVerificationResult> VerifyAsync(
            AttestationVerificationRequest request, CancellationToken cancellationToken)
        {
            _calls.Add("attestation.verify");

            return Task.FromResult(IsAccepted
                ? AttestationVerificationResult.Accepted(Level)
                : AttestationVerificationResult.Rejected(ReasonCode));
        }
    }

    internal sealed class FakeSignatureVerifier : IRequestSignatureVerifier
    {
        private readonly List<string> _calls;

        public FakeSignatureVerifier(List<string> calls) => _calls = calls;

        public bool IsValid { get; set; } = true;

        public bool Verify(ReadOnlySpan<byte> signatureBase, ReadOnlySpan<byte> signature, ReadOnlySpan<byte> publicKey)
        {
            _calls.Add("signatures.verify");
            return IsValid;
        }
    }

    internal sealed class FakeSecurityEventRecorder : ISecurityEventRecorder
    {
        private readonly List<string> _calls;

        public FakeSecurityEventRecorder(List<string> calls) => _calls = calls;

        public List<SecurityEvent> Events { get; } = [];

        public Task RecordAsync(SecurityEvent securityEvent, CancellationToken cancellationToken)
        {
            _calls.Add("securityEvents.record");
            Events.Add(securityEvent);
            return Task.CompletedTask;
        }
    }
}
