/*==============================================================================
  mobile.usp_Device_IssueRegistrationChallenge
  Phase : 6
  Called by: POST /api/v1/mobile/device/registration/challenge

  Purpose
  -------
  Issue a single-use, short-lived challenge that the device embeds in its
  platform key attestation. Binding the attestation to a server-issued value
  is what prevents an attacker replaying a previously captured attestation
  (threat TH-10).

  The challenge bytes are generated by the application using a cryptographic
  random number generator and passed in; this procedure only persists them
  with an expiry. Key material and randomness generation stay in one place in
  the application's crypto services rather than being spread across layers.

  The response to the caller is deliberately identical whether or not any
  particular employee exists: no user is referenced here at all, so the
  endpoint cannot be used to enumerate accounts.

  Result codes
      0    Success
==============================================================================*/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE mobile.usp_Device_IssueRegistrationChallenge
    @Challenge        VARBINARY(32),
    @LifetimeSeconds  INT,
    @IssuedToIpHash   VARBINARY(32) = NULL,
    @ChallengeId      UNIQUEIDENTIFIER OUTPUT,
    @ExpiresUtc       DATETIME2(3)     OUTPUT,
    @ResultCode       INT              OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @NowUtc DATETIME2(3) = SYSUTCDATETIME();

    SET @ChallengeId = NEWID();
    SET @ExpiresUtc  = DATEADD(SECOND, @LifetimeSeconds, @NowUtc);

    INSERT INTO core.DeviceRegistrationChallenge
        (ChallengeId, Challenge, IssuedUtc, ExpiresUtc, IssuedToIpHash)
    VALUES
        (@ChallengeId, @Challenge, @NowUtc, @ExpiresUtc, @IssuedToIpHash);

    SET @ResultCode = 0;
END;
GO

PRINT 'mobile.usp_Device_IssueRegistrationChallenge deployed.';
GO
