using Attendance.Domain.Enums;
using Attendance.Domain.ValueObjects;

namespace Attendance.Application.Abstractions;

/// <summary>
/// Device registration and lookup, backed by the <c>mobile</c> stored procedures.
/// </summary>
/// <remarks>
/// <para>
/// <b>This port deliberately carries no administrative operation.</b> Approving
/// or revoking a device lives in the <c>admin</c> schema, and the mobile
/// application's database account is explicitly denied execute permission on it
/// (<c>DENY EXECUTE ON SCHEMA::[admin]</c>, so that a compromised internet-facing
/// API process cannot call an administrative procedure — threat TH-28). Declaring
/// an approval method here would describe something the runtime identity cannot
/// do. The administration portal gets its own port against its own schema.
/// </para>
/// <para>
/// Every member maps to exactly one stored procedure (Claude.md §4).
/// </para>
/// </remarks>
public interface IDeviceRepository
{
    /// <summary>
    /// Records a single-use registration challenge and returns its identifier.
    /// </summary>
    /// <remarks>
    /// The challenge bytes are generated by the caller with a cryptographic RNG;
    /// the database only stores them with an expiry. Binding the platform
    /// attestation to a server-issued value is what stops a previously captured
    /// attestation being replayed (threat TH-10).
    /// </remarks>
    Task<RegistrationChallenge> IssueRegistrationChallengeAsync(
        ReadOnlyMemory<byte> challenge,
        int lifetimeSeconds,
        byte[]? issuedToIpHash,
        CancellationToken cancellationToken);

    /// <summary>
    /// Registers a device against a consumed challenge.
    /// </summary>
    /// <remarks>
    /// The caller must already have verified the password, the authenticator
    /// code, the platform attestation and proof of possession of the private key.
    /// The procedure owns what must be atomic: consuming the challenge exactly
    /// once, refusing a key already bound elsewhere, and applying DEC-04.
    /// </remarks>
    Task<DeviceRegistrationOutcome> RegisterAsync(
        DeviceRegistrationRequest request,
        CancellationToken cancellationToken);

    /// <summary>
    /// Returns where a device's own registration stands.
    /// </summary>
    /// <remarks>
    /// Reachable by a device that is not yet active: a pending device has to be
    /// able to ask whether it has been approved. The signature is still verified,
    /// so only the real device can ask — what is relaxed is the status
    /// requirement, not the authentication.
    /// </remarks>
    Task<DeviceStatusRecord?> GetStatusAsync(Guid devicePublicId, CancellationToken cancellationToken);

    /// <summary>
    /// Returns the material needed to verify a request signature and decide
    /// whether the device may act.
    /// </summary>
    /// <remarks>
    /// Read on every signed request and never cached: revocation has to take
    /// effect immediately (§18), and a cache would leave a revoked device working
    /// until the entry expired. The row is returned even when the device is
    /// unusable, so the API can write a meaningful security event — callers must
    /// act on <see cref="DeviceVerificationRecord.ResultCode"/>, never on the
    /// mere presence of a row.
    /// </remarks>
    Task<DeviceVerificationRecord?> GetForSignatureVerificationAsync(
        Guid devicePublicId,
        CancellationToken cancellationToken);

    /// <summary>
    /// Records that an active device was seen.
    /// </summary>
    /// <remarks>
    /// Deliberately outside the attendance transaction: it is not part of the
    /// attendance integrity guarantee and must never lengthen a transaction
    /// holding attendance locks (§30). Only active devices are touched, so a
    /// revoked device keeps showing when it was last legitimately used.
    /// </remarks>
    Task TouchLastSeenAsync(
        int deviceId,
        string? appVersion,
        string? osVersion,
        CancellationToken cancellationToken);
}

/// <summary>
/// Where a device registration stands.
/// </summary>
/// <remarks>
/// Values match the <c>Status</c> column on <c>core.Device</c> and its
/// <c>CK_Device_Status</c> check constraint.
/// </remarks>
public enum DeviceStatus
{
    /// <summary>Registered, awaiting administrator approval. Cannot record attendance.</summary>
    PendingApproval = 0,

    /// <summary>Approved and usable.</summary>
    Active = 1,

    /// <summary>Revoked. Cannot record attendance, and never becomes usable again.</summary>
    Revoked = 2,
}

/// <summary>
/// How strongly a device's key was attested at registration.
/// </summary>
/// <remarks>
/// <para>
/// Values match <c>core.Device.AttestationLevel</c> and its
/// <c>CK_Device_AttestationLevel</c> constraint.
/// </para>
/// <para>
/// <b>This is a statement about the key, not a guarantee about the device.</b>
/// Hardware attestation shows a key was generated inside a secure element and
/// cannot be exported; it does not prove the handset is uncompromised (§65).
/// </para>
/// </remarks>
public enum AttestationLevel
{
    /// <summary>No attestation was presented or it could not be verified.</summary>
    None = 0,

    /// <summary>The key is held in software and could in principle be extracted.</summary>
    Software = 1,

    /// <summary>The key is hardware-backed and non-exportable.</summary>
    Hardware = 2,
}

/// <summary>A challenge issued for one device registration attempt.</summary>
/// <param name="ResultCode">The procedure's outcome.</param>
/// <param name="ChallengeId">Identifier the client returns with its attestation.</param>
/// <param name="ExpiresUtc">When the challenge stops being usable.</param>
public readonly record struct RegistrationChallenge(
    AttendanceResultCode ResultCode,
    Guid ChallengeId,
    DateTimeOffset ExpiresUtc);

/// <summary>
/// A request to register a device, after every check the application owns.
/// </summary>
/// <param name="ChallengeId">The challenge being consumed.</param>
/// <param name="Challenge">Its bytes, checked against the stored value.</param>
/// <param name="MobileUserId">The authenticated employee.</param>
/// <param name="PublicKey">Uncompressed P-256 point: 0x04 ‖ X(32) ‖ Y(32).</param>
/// <param name="PublicKeyThumbprint">SHA-256 of that point; carries uniqueness.</param>
/// <param name="Platform">Android or iOS.</param>
/// <param name="AttestationLevel">The level the verifier established.</param>
/// <param name="DeviceModel">Untrusted client metadata, printable ASCII only.</param>
/// <param name="OsVersion">Untrusted client metadata.</param>
/// <param name="AppVersion">Untrusted client metadata.</param>
/// <param name="RequiresApproval">
/// From <c>Security.DeviceRegistrationRequiresApproval</c> (OPEN-32). Even when
/// false, the procedure still refuses to displace an existing active device:
/// replacing a device is always an administrative act.
/// </param>
/// <param name="CorrelationId">Ties the registration to its audit entry.</param>
public readonly record struct DeviceRegistrationRequest(
    Guid ChallengeId,
    ReadOnlyMemory<byte> Challenge,
    int MobileUserId,
    byte[] PublicKey,
    byte[] PublicKeyThumbprint,
    DevicePlatform Platform,
    AttestationLevel AttestationLevel,
    string? DeviceModel,
    string? OsVersion,
    string? AppVersion,
    bool RequiresApproval,
    Guid CorrelationId);

/// <summary>The outcome of a registration.</summary>
/// <param name="ResultCode">
/// <see cref="AttendanceResultCode.Success"/> when the device is active, or
/// <see cref="AttendanceResultCode.RegistrationPendingApproval"/> when it was
/// created and awaits approval. Both mean a device row exists.
/// </param>
/// <param name="DevicePublicId">The new device's external identifier.</param>
/// <param name="Status">The status it was created with.</param>
public readonly record struct DeviceRegistrationOutcome(
    AttendanceResultCode ResultCode,
    Guid? DevicePublicId,
    DeviceStatus? Status);

/// <summary>A device's own view of its registration.</summary>
/// <param name="ResultCode">The procedure's outcome.</param>
/// <param name="DevicePublicId">The device asked about.</param>
/// <param name="Status">Pending, active or revoked.</param>
/// <param name="AttestationLevel">The level recorded at registration.</param>
/// <param name="RegisteredUtc">When it was registered.</param>
/// <param name="ApprovedUtc">When it was approved, if it was.</param>
/// <param name="RevokedUtc">When it was revoked, if it was.</param>
/// <param name="RevokedReason">
/// Shown to the holder of the device, who is the person who needs to know why it
/// stopped working. It never mentions another employee or another device.
/// </param>
/// <param name="MobileUserPublicId">The employee it is bound to.</param>
/// <param name="UserId">That employee's sign-in identifier.</param>
/// <param name="EmployeeActive">Whether that employee is still active.</param>
/// <param name="ServerTimeUtc">Server time, so the app can detect its own drift.</param>
public readonly record struct DeviceStatusRecord(
    AttendanceResultCode ResultCode,
    Guid DevicePublicId,
    DeviceStatus Status,
    AttestationLevel AttestationLevel,
    DateTimeOffset RegisteredUtc,
    DateTimeOffset? ApprovedUtc,
    DateTimeOffset? RevokedUtc,
    string? RevokedReason,
    Guid MobileUserPublicId,
    string UserId,
    bool EmployeeActive,
    DateTimeOffset ServerTimeUtc);

/// <summary>
/// What the signature middleware needs to authenticate one request.
/// </summary>
/// <param name="ResultCode">
/// Whether the device may act. <b>This is the authority</b>, not the presence of
/// the record.
/// </param>
/// <param name="DeviceId">Internal identifier.</param>
/// <param name="DevicePublicId">The <c>keyid</c> carried in the signature.</param>
/// <param name="MobileUserId">The employee the device is bound to.</param>
/// <param name="MobileUserPublicId">That employee's external identifier.</param>
/// <param name="UserId">That employee's sign-in identifier.</param>
/// <param name="PublicKey">The registered P-256 point to verify against.</param>
/// <param name="Status">The device's status.</param>
/// <param name="AttestationLevel">The level recorded at registration.</param>
/// <param name="Platform">Android or iOS.</param>
/// <param name="AppVersion">Last reported version; never an authorization input.</param>
public readonly record struct DeviceVerificationRecord(
    AttendanceResultCode ResultCode,
    int DeviceId,
    Guid DevicePublicId,
    int MobileUserId,
    Guid MobileUserPublicId,
    string UserId,
    byte[] PublicKey,
    DeviceStatus Status,
    AttestationLevel AttestationLevel,
    DevicePlatform Platform,
    string? AppVersion);
